import { useState } from "react";
import type { Student, VocabQuizAttempt } from "../services/database";

type Props = { students: Student[]; attempts: VocabQuizAttempt[] };
type AbilityMode = "accuracy" | "time" | "joint";
const fmt = (n: number | null) => n === null ? "--" : `${(n / 1000).toFixed(1)}s`;
const median = (xs: number[]) => { if (!xs.length) return null; const a = [...xs].sort((x, y) => x - y); const i = Math.floor(a.length / 2); return a.length % 2 ? a[i] : (a[i - 1] + a[i]) / 2; };

export default function AdminIrtStudentPanel({ students, attempts }: Props) {
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [mode, setMode] = useState<AbilityMode>("joint");
  const rows = students.map((student) => { const as = attempts.filter((a) => a.studentId === student.id || (!a.studentId && a.studentName === student.name)); const responses = as.flatMap((a) => a.questionResults ?? []); const correct = responses.filter((r) => r.correct).length; const accuracy = responses.length ? correct / responses.length : null; const accuracyAbility = accuracy === null ? null : Math.max(-4, Math.min(4, Math.log(Math.max(.01, accuracy) / Math.max(.01, 1 - accuracy)))); const times = responses.map((r) => r.timeMs).filter((t): t is number => Number.isFinite(t) && t >= 0); const meanLog = times.length ? times.reduce((s, t) => s + Math.log(Math.max(t, 1)), 0) / times.length : null; return { student, responses, accuracy, accuracyAbility, times, avgTime: times.length ? times.reduce((s, t) => s + t, 0) / times.length : null, medianTime: median(times), items: new Set(responses.map((r) => r.word)).size, meanLog }; });
  const allTimes = rows.flatMap((r) => r.times); const globalLog = allTimes.length ? allTimes.reduce((s, t) => s + Math.log(Math.max(t, 1)), 0) / allTimes.length : null;
  const abilityFor = (row: typeof rows[number]) => { const timeAbility = row.meanLog === null || globalLog === null ? null : globalLog - row.meanLog; if (mode === "accuracy") return row.accuracyAbility; if (mode === "time") return timeAbility; return row.accuracyAbility === null || timeAbility === null ? null : (row.accuracyAbility + timeAbility) / 2; };
  const selected = rows.find((r) => r.student.id === selectedId) ?? null;
  const label = mode === "accuracy" ? "Accuracy ability" : mode === "time" ? "Response-time ability" : "Joint speed + accuracy";
  const modeSupport = mode === "accuracy"
    ? { formula: "θ = log(p / (1 − p))", detail: "p is the student's observed correct-response proportion.", paper: "Rasch model / 1PL measurement foundation", url: "https://www.rasch.org/memo41.htm" }
    : mode === "time"
      ? { formula: "speed = mean(log(sample time)) − mean(log(student time))", detail: "Higher values mean faster response times than the sample average.", paper: "van der Linden (2006), Lognormal Response-Time Model", url: "https://doi.org/10.1111/j.1745-3984.2006.00013.x" }
      : { formula: "joint = (accuracy ability + response-time ability) / 2", detail: "A transparent pilot composite; not a full hierarchical speed-accuracy fit.", paper: "van der Linden (2007), A Hierarchical Framework for Modeling Speed and Accuracy", url: "https://ris.utwente.nl/ws/files/5129699/Linden05hierarchical.pdf" };
  return <section className="admin-irt-panel"><div className="admin-irt-modebar"><label>Ability view<select value={mode} onChange={(e) => setMode(e.target.value as AbilityMode)}><option value="joint">Joint accuracy + response time</option><option value="accuracy">Accuracy only</option><option value="time">Response time only</option></select></label><div><strong>{label}</strong><code>{modeSupport.formula}</code><span>{modeSupport.detail}</span><small>Paper support: <a href={modeSupport.url} target="_blank" rel="noreferrer">{modeSupport.paper}</a></small></div></div><div className="admin-irt-note"><strong>Interpretation note</strong><p>These are provisional student-level monitoring estimates. Official IRT calibration requires stable item identity, item parameters, and sufficient responses; do not use this view for high-stakes decisions.</p></div><section className="account-table admin-irt-table"><div className="table-head"><span>Student</span><span>Responses</span><span>Accuracy</span><span>Ability</span><span>Median time</span><span>Status</span></div>{rows.map((row) => <button className={`account-row ${selectedId === row.student.id ? "selected" : ""}`} key={row.student.id} onClick={() => setSelectedId(row.student.id)}><span><b>{row.student.name}</b></span><span>{row.responses.length}</span><span>{row.accuracy === null ? "--" : `${Math.round(row.accuracy * 100)}%`}</span><span>{abilityFor(row) === null ? "--" : abilityFor(row)!.toFixed(2)}</span><span>{fmt(row.medianTime)}</span><span><em className={row.responses.length >= 30 ? "active" : "inactive"}>{row.responses.length >= 30 ? "Ready to review" : "Collecting data"}</em></span></button>)}</section>{selected && <aside className="admin-irt-detail"><div><h2>{selected.student.name}</h2><button type="button" onClick={() => setSelectedId(null)}>Close</button></div><div className="admin-irt-detail-grid"><div><span>{label}</span><strong>{abilityFor(selected) === null ? "--" : abilityFor(selected)!.toFixed(2)}</strong></div><div><span>Accuracy</span><strong>{selected.accuracy === null ? "--" : `${Math.round(selected.accuracy * 100)}%`}</strong></div><div><span>Responses</span><strong>{selected.responses.length}</strong></div><div><span>Median time</span><strong>{fmt(selected.medianTime)}</strong></div></div></aside>}</section>;
}
