import { BACKEND_URL, clientRoleHeader, fetchWithRetry, REQUEST_TIMEOUT_MS, VOCAB_GENERATION_RETRY_STATUSES } from "./client";
export interface VocabGrowthWord { word: string; translation: string; context?: string; avoid: string[]; }
export interface VocabularyDistractorUpdate { frameIndex: number; wordIndex: number; distractors: string[]; }
export interface VocabularyClozeCandidate { sentence: string; distractors: string[]; }
export interface VocabularyClozeUpdate { frameIndex: number; wordIndex: number; candidates: VocabularyClozeCandidate[]; }
export interface VocabularySynonymCandidate { synonym: string; distractors: string[]; }
export interface VocabularySynonymUpdate { frameIndex: number; wordIndex: number; candidates: VocabularySynonymCandidate[]; }
export interface QuizValidateWord { word: string; translation?: string; distractors: string[]; cloze: Array<{ sentence: string; distractors: string[] }>; synonym: Array<{ synonym: string; distractors: string[] }>; }
export interface QuizValidateResultItem { word: string; kind: "translation" | "distractors" | "cloze" | "synonym"; poolIndex?: number; status: "clean" | "suspicious"; reason: string; }
export interface VocabQuizAttempt { id: string; storyId: string; studentName: string; studentId?: string; mode?: "tier1" | "tier2" | "tier3" | "speed" | "strikes" | "free" | "weak_words"; baseStoryId?: string; level?: "easy" | "medium" | "hard"; completedAt: string; totalQuestions: number; correctCount: number; totalTimeMs: number; questionResults: Array<{ word: string; correct: boolean; timeMs: number; itemId?: string; conceptId?: string; questionKind?: string; level?: "easy" | "medium" | "hard"; baseStoryId?: string; itemVersion?: string; selectedAnswer?: string; correctAnswer?: string; presentedOptions?: string[]; questionPrompt?: string; answeredAt?: string; questionIndex?: number; lessonId?: string; quizId?: string; isBktEligible?: boolean; bktEligibilityErrors?: string[]; diagnosticExposureId?: string; assistedResponse?: boolean; bktValidationStatus?: "APPROVED" | "DRAFT" }>; }
async function generate<T>(path: string, words: VocabGrowthWord[], errorMessage: string): Promise<T[]> { const response = await fetchWithRetry(`${BACKEND_URL}${path}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ words }) }, 3, REQUEST_TIMEOUT_MS, VOCAB_GENERATION_RETRY_STATUSES); if (!response.ok) throw new Error(errorMessage); return ((await response.json()) as { results: T[] }).results; }
export function generateVocabDistractors(words: VocabGrowthWord[]): Promise<Array<{ word: string; distractors: string[] }>> { return generate("/api/vocab-quiz-distractors", words, "Could not generate new quiz distractors."); }
export function generateVocabCloze(words: VocabGrowthWord[]): Promise<Array<{ word: string; sentence: string; distractors: string[] }>> { return generate("/api/vocab-quiz-cloze", words, "Could not generate new quiz cloze questions."); }
export function generateVocabSynonym(words: VocabGrowthWord[]): Promise<Array<{ word: string; synonym: string; distractors: string[] }>> { return generate("/api/vocab-quiz-synonym", words, "Could not generate new quiz synonym questions."); }
async function patchPool(storyId: string, path: string, updates: unknown, message: string): Promise<void> {
  // Pool editing is teacher/admin work. Students can finish a quiz, but they
  // must not try to mutate published question material and receive a 403.
  if (clientRoleHeader() === "student") return;
  const response = await fetchWithRetry(`${BACKEND_URL}/api/custom-stories/${encodeURIComponent(storyId)}/${path}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ updates }) });
  if (!response.ok) throw new Error(message);
}
export function updateVocabularyDistractors(storyId: string, updates: VocabularyDistractorUpdate[]): Promise<void> { return patchPool(storyId, "vocabulary-distractors", updates, "Could not update vocabulary distractors for the story."); }
export function updateVocabularyCloze(storyId: string, updates: VocabularyClozeUpdate[]): Promise<void> { return patchPool(storyId, "vocabulary-cloze", updates, "Could not update vocabulary cloze questions for the story."); }
export function updateVocabularySynonym(storyId: string, updates: VocabularySynonymUpdate[]): Promise<void> { return patchPool(storyId, "vocabulary-synonym", updates, "Could not update vocabulary synonym questions for the story."); }
export async function updateQuizExclusions(storyId: string, exclusions: Array<{ word: string; kind: string; index?: number }>, materialSnapshot?: Record<string, unknown>): Promise<void> { const response = await fetchWithRetry(`${BACKEND_URL}/api/custom-stories/${encodeURIComponent(storyId)}/quiz-exclusions`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ exclusions, materialSnapshot }) }); if (!response.ok) throw new Error("Could not save the quiz exclusion list."); }
export async function validateQuizMaterial(storyId: string, words: QuizValidateWord[], exclusions: Array<{ word: string; kind: string; index?: number }>): Promise<QuizValidateResultItem[]> { const response = await fetchWithRetry(`${BACKEND_URL}/api/custom-stories/${encodeURIComponent(storyId)}/quiz/validate`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ words, exclusions }) }, 3, 60_000); if (!response.ok) throw new Error("Could not validate the quiz questions."); return ((await response.json()) as { results: QuizValidateResultItem[] }).results; }
export async function approveQuizMaterial(storyId: string, level: string, material: QuizValidateWord[]): Promise<void> { const response = await fetchWithRetry(`${BACKEND_URL}/api/custom-stories/${encodeURIComponent(storyId)}/quiz/approve`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ level, material }) }); if (!response.ok) throw new Error("Could not publish the quiz."); }
export async function saveQuizPendingApprovals(storyId: string, level: string, approvals: Array<{ word: string; kind: string; index?: number }>): Promise<void> { const response = await fetchWithRetry(`${BACKEND_URL}/api/custom-stories/${encodeURIComponent(storyId)}/quiz-pending-approvals`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ level, approvals }) }); if (!response.ok) throw new Error("Could not save the quiz review selections."); }
export async function replaceQuizQuestion(storyId: string, frameIndex: number, wordIndex: number, kind: "translation" | "distractors" | "cloze" | "synonym" | "pinyin", poolIndex: number | undefined, value: string | string[] | { sentence: string; distractors: string[] } | { synonym: string; distractors: string[] }, translationField?: "vocabularyTranslation" | "vocabularyTranslationMedium" | "vocabularyTranslationHard", pinyinField?: "vocabularyPinyin" | "vocabularyPinyinMedium" | "vocabularyPinyinHard"): Promise<void> { const response = await fetchWithRetry(`${BACKEND_URL}/api/custom-stories/${encodeURIComponent(storyId)}/quiz-question`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ frameIndex, wordIndex, kind, poolIndex, value, translationField, pinyinField }) }); if (!response.ok) throw new Error("Could not save the edited question."); }
export async function createVocabQuizAttempt(attempt: VocabQuizAttempt): Promise<VocabQuizAttempt> { const response = await fetchWithRetry(`${BACKEND_URL}/api/vocab-quiz-attempts`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(attempt) }); if (!response.ok) throw new Error("Could not save the vocabulary quiz attempt."); return response.json() as Promise<VocabQuizAttempt>; }
export async function recordVocabQuizResponse(attempt: VocabQuizAttempt): Promise<void> { const response = await fetchWithRetry(`${BACKEND_URL}/api/vocab-quiz-responses`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(attempt) }); if (!response.ok) throw new Error("Could not save the vocabulary quiz response."); }
export async function listVocabQuizAttempts(storyId?: string, student?: { studentId?: string; studentName?: string }): Promise<VocabQuizAttempt[]> { const params = new URLSearchParams(); if (storyId) params.set("story_id", storyId); if (student?.studentId) params.set("student_id", student.studentId); else if (student?.studentName) params.set("student_name", student.studentName); const query = params.toString(); const response = await fetchWithRetry(query ? `${BACKEND_URL}/api/vocab-quiz-attempts?${query}` : `${BACKEND_URL}/api/vocab-quiz-attempts`); if (!response.ok) throw new Error("Could not load vocabulary quiz attempts."); const data = await response.json(); return Array.isArray(data) ? data : []; }
export interface VocabPriorityReviewWord { wordId: string; word: string; meaning?: string | null; pLearned: number; status: "UNASSESSED" | "NEEDS_REVIEW" | "DEVELOPING" | "MASTERED"; observationCount: number; correctCount: number; incorrectCount: number; lastResponseAt?: string | null; lastItemId?: string | null; lessonId?: string | null; seenQuestionTypes?: string[]; }
export interface VocabPriorityReviewResponse { unlocked: boolean; requiredDiagnosticQuizzes: number; completedDiagnosticQuizzes: number; reviewCount: number; words: VocabPriorityReviewWord[]; mastery?: VocabPriorityReviewWord[]; }
export async function getVocabQuizPriorityReview(storyId: string | undefined, studentId: string, options?: { includeAllWeak?: boolean }): Promise<VocabPriorityReviewResponse> { const params = new URLSearchParams(); if (storyId) params.set("story_id", storyId); if (options?.includeAllWeak) params.set("include_all", "true"); const query = params.toString(); const response = await fetchWithRetry(`${BACKEND_URL}/api/students/${encodeURIComponent(studentId)}/weak-words${query ? `?${query}` : ""}`); if (!response.ok) throw new Error("Could not load personalized review."); return response.json() as Promise<VocabPriorityReviewResponse>; }
/** Compatibility-shaped helper used by the existing per-story quiz picker.
 * The story picker asks for the complete cumulative weak-word set, while the
 * endpoint can still serve a smaller Bottom-K result to other callers. */
export type VocabWeakWordsResult = string[] & { diagnostic?: Pick<VocabPriorityReviewResponse, "unlocked" | "requiredDiagnosticQuizzes" | "completedDiagnosticQuizzes">; priorityReview?: VocabPriorityReviewWord[] };
export async function getVocabQuizWeakWords(storyId: string, student: { studentId?: string; studentName?: string }): Promise<VocabWeakWordsResult> { if (!student.studentId) return []; const data = await getVocabQuizPriorityReview(storyId, student.studentId, { includeAllWeak: true }); const words = data.words.map((word) => word.word) as VocabWeakWordsResult; Object.defineProperty(words, "diagnostic", { value: { unlocked: data.unlocked, requiredDiagnosticQuizzes: data.requiredDiagnosticQuizzes, completedDiagnosticQuizzes: data.completedDiagnosticQuizzes }, enumerable: false }); Object.defineProperty(words, "priorityReview", { value: data.words, enumerable: false }); return words; }
