import { BACKEND_URL, fetchWithRetry } from "./client";
export interface HelpRequest { id: string; studentName: string; message: string; status: "open" | "resolved"; createdAt: string; resolvedAt?: string | null; }
export interface Student { id: string; name: string; createdAt: string; status: "active" | "inactive"; }
export interface Teacher { id: string; name: string; createdAt: string; status: "active" | "inactive"; }
export async function listHelpRequests(): Promise<HelpRequest[]> { const response = await fetchWithRetry(`${BACKEND_URL}/api/help-requests`); if (!response.ok) throw new Error("Could not load help requests from the database."); const requests = await response.json(); return Array.isArray(requests) ? requests : []; }
export async function createHelpRequest(request: HelpRequest): Promise<HelpRequest> { const response = await fetchWithRetry(`${BACKEND_URL}/api/help-requests`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(request) }); if (!response.ok) throw new Error("Could not send the help request."); return response.json() as Promise<HelpRequest>; }
export async function resolveHelpRequest(id: string): Promise<HelpRequest> { const response = await fetchWithRetry(`${BACKEND_URL}/api/help-requests/${encodeURIComponent(id)}/resolve`, { method: "POST" }); if (!response.ok) throw new Error("Could not resolve the help request."); return response.json() as Promise<HelpRequest>; }
export async function listStudents(): Promise<Student[]> { const response = await fetchWithRetry(`${BACKEND_URL}/api/students`); if (!response.ok) throw new Error("Could not load the student roster."); const data = await response.json(); return Array.isArray(data) ? data : []; }
export async function loginStudent(params: { studentId?: string; name?: string; password: string }): Promise<Student> { const response = await fetchWithRetry(`${BACKEND_URL}/api/students/login`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(params) }); if (response.status === 401 || response.status === 404) { const error = new Error("Wrong name or password."); (error as Error & { wrongCredentials?: boolean; notFound?: boolean }).wrongCredentials = true; (error as Error & { wrongCredentials?: boolean; notFound?: boolean }).notFound = response.status === 404; throw error; } if (!response.ok) throw new Error("Could not sign in."); return response.json() as Promise<Student>; }
export async function logoutStudent(): Promise<void> { await fetchWithRetry(`${BACKEND_URL}/api/students/logout`, { method: "POST" }); }
export async function createStudent(name: string, password: string): Promise<Student> { const response = await fetchWithRetry(`${BACKEND_URL}/api/students`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, password }) }); if (!response.ok) throw new Error("Could not add the student to the roster."); return response.json() as Promise<Student>; }
export async function deleteStudent(id: string): Promise<void> { const response = await fetchWithRetry(`${BACKEND_URL}/api/students/${encodeURIComponent(id)}`, { method: "DELETE" }); if (!response.ok) throw new Error("Could not remove the student from the roster."); }
export async function updateStudent(id: string, update: { name?: string; password?: string; status?: "active" | "inactive" }): Promise<Student> { const response = await fetchWithRetry(`${BACKEND_URL}/api/students/${encodeURIComponent(id)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(update) }); if (response.status === 409) throw new Error("Student already exists."); if (!response.ok) throw new Error("Could not update student account."); return response.json() as Promise<Student>; }
export async function listTeachers(): Promise<Teacher[]> { const response = await fetchWithRetry(`${BACKEND_URL}/api/teachers`); if (!response.ok) throw new Error("Could not load teacher accounts."); const data = await response.json(); return Array.isArray(data) ? data : []; }
export async function createTeacher(name: string, password: string): Promise<Teacher> { const response = await fetchWithRetry(`${BACKEND_URL}/api/teachers`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, password }) }); if (!response.ok) throw new Error(response.status === 409 ? "Teacher already exists." : "Could not create teacher account."); return response.json() as Promise<Teacher>; }
export async function loginTeacher(name: string, password: string): Promise<Teacher> { const response = await fetchWithRetry(`${BACKEND_URL}/api/teachers/login`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, password }) }); if (!response.ok) throw new Error(response.status === 403 ? "Teacher account is inactive." : "Wrong teacher name or password."); return response.json() as Promise<Teacher>; }
export async function logoutTeacher(): Promise<void> { await fetchWithRetry(`${BACKEND_URL}/api/teachers/logout`, { method: "POST" }); }
export async function updateTeacher(id: string, update: { name?: string; password?: string; status?: "active" | "inactive" }): Promise<Teacher> { const response = await fetchWithRetry(`${BACKEND_URL}/api/teachers/${encodeURIComponent(id)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(update) }); if (response.status === 409) throw new Error("Teacher already exists."); if (!response.ok) throw new Error("Could not update teacher account."); return response.json() as Promise<Teacher>; }
export async function deleteTeacher(id: string): Promise<void> { const response = await fetchWithRetry(`${BACKEND_URL}/api/teachers/${encodeURIComponent(id)}`, { method: "DELETE" }); if (!response.ok) throw new Error("Could not delete teacher account."); }
export async function loginAdmin(password: string): Promise<void> { const response = await fetchWithRetry(`${BACKEND_URL}/api/admin/login`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password }) }); if (!response.ok) throw new Error(response.status === 503 ? "Admin login is not configured." : "Wrong admin password."); }
export async function logoutAdmin(): Promise<void> { await fetchWithRetry(`${BACKEND_URL}/api/admin/logout`, { method: "POST" }); }
