import { BACKEND_URL, fetchWithRetry } from "./client";

export type NarrativeMode = "story" | "describe" | "listen_retell";
export interface CustomStoryFrame { imageUrl: string; prompt: string; vocabulary: string; vocabularyGroups?: Array<{ name: string; words: string[] }>; phrases?: string; phrasesTranslation?: string; vocabularyPinyin?: string; vocabularyPos?: string; vocabularyTranslation?: string; vocabularyDistractors?: string; vocabularyCloze?: string; vocabularySynonym?: string; suggestedAnswer?: string; listenAudioUrl?: string; listenScript?: string; imageUrlMedium?: string; imageUrlHard?: string; promptMedium?: string; promptHard?: string; vocabularyMedium?: string; vocabularyHard?: string; vocabularyPinyinMedium?: string; vocabularyPinyinHard?: string; vocabularyPosMedium?: string; vocabularyPosHard?: string; vocabularyTranslationMedium?: string; vocabularyTranslationHard?: string; phrasesMedium?: string; phrasesHard?: string; phrasesTranslationMedium?: string; phrasesTranslationHard?: string; suggestedAnswerMedium?: string; suggestedAnswerHard?: string; listenAudioUrlMedium?: string; listenAudioUrlHard?: string; listenScriptMedium?: string; listenScriptHard?: string; }
export interface StoredCustomStory { id: string; title: string; learningGoal: string; frames: CustomStoryFrame[]; published?: boolean; linear?: boolean; firstFrameIsExample?: boolean; rubricScores?: Record<string, unknown> | null; lessonNumber?: number | null; lessonSubOrder?: number | null; narrativeMode?: NarrativeMode; }
export interface SceneSubmission { sceneIndex: number; imageUrl: string; transcription: string; vocabUsed: string[]; vocabMissing: string[]; vocabScore: number; toneAccuracy: number; pronScore: number; fluencyScore?: number; audioUrl?: string; pauseCount?: number; longestPause?: number; utteranceCount?: number; choppyPauseCount?: number; articulationRate?: number; selfEvalContent?: "good" | "ok" | "bad"; selfEvalPronunciation?: "good" | "ok" | "bad"; baseStoryId?: string; difficultyLevel?: "easy" | "medium" | "hard"; promptId?: string; }
export interface StoryFeedbackDimension { score: number; feedback: string; judged?: boolean; }
export interface StoryFeedback { provider: string; tone: StoryFeedbackDimension; word_stress: StoryFeedbackDimension; rhythm_pace: StoryFeedbackDimension; pausing: StoryFeedbackDimension; }
export interface StorySubmission { id: string; storyId: string; storyTitle: string; studentName: string; studentId?: string; submittedAt: string; scenes: SceneSubmission[]; concatenatedAudioUrl?: string | null; storyFeedback?: StoryFeedback | null; reviewStatus: "pending" | "reviewed"; teacherNote?: string | null; }

export async function listCustomStories(): Promise<StoredCustomStory[]> { const response = await fetchWithRetry(`${BACKEND_URL}/api/custom-stories`); if (!response.ok) throw new Error("Could not load custom stories from the database."); const stories = await response.json(); return Array.isArray(stories) ? stories : []; }
export async function createCustomStory(story: StoredCustomStory): Promise<StoredCustomStory> { const response = await fetchWithRetry(`${BACKEND_URL}/api/custom-stories`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(story) }); if (!response.ok) throw new Error("Could not save custom story to the database."); return response.json() as Promise<StoredCustomStory>; }
export async function deleteCustomStoryFromDatabase(id: string): Promise<void> { const response = await fetchWithRetry(`${BACKEND_URL}/api/custom-stories/${encodeURIComponent(id)}`, { method: "DELETE" }); if (!response.ok) throw new Error("Could not delete custom story from the database."); }
export async function listStorySubmissions(storyId?: string, student?: { studentId?: string; studentName?: string }): Promise<StorySubmission[]> { const params = new URLSearchParams(); if (storyId) params.set("story_id", storyId); if (student?.studentId) params.set("student_id", student.studentId); else if (student?.studentName) params.set("student_name", student.studentName); const query = params.toString(); const response = await fetchWithRetry(query ? `${BACKEND_URL}/api/story-submissions?${query}` : `${BACKEND_URL}/api/story-submissions`); if (!response.ok) throw new Error("Could not load story submissions."); const data = await response.json(); return Array.isArray(data) ? data : []; }
export async function createStorySubmission(submission: Omit<StorySubmission, "reviewStatus" | "teacherNote">): Promise<StorySubmission> { const response = await fetchWithRetry(`${BACKEND_URL}/api/story-submissions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(submission) }); if (!response.ok) throw new Error("Could not submit story."); return response.json() as Promise<StorySubmission>; }
export async function updateSubmissionReview(id: string, status: "pending" | "reviewed", note?: string | null): Promise<StorySubmission> { const response = await fetchWithRetry(`${BACKEND_URL}/api/story-submissions/${encodeURIComponent(id)}/review`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status, note }) }); if (!response.ok) throw new Error("Could not update story submission review."); return response.json() as Promise<StorySubmission>; }
