import { useState } from "react";
import type {
  BktTraceStep,
  EvidenceItem,
  GoldenCheck,
  LiveTrace,
  VerificationResult,
  VerificationStudent,
  VerificationWord,
} from "../../services/api/bkt-verification";

export function formatProbability(value: number): string {
  return value.toFixed(6);
}

export function formatQuestionType(value: string | null | undefined): string {
  if (!value) return "—";
  return {
    basic_meaning_mcq: "Basic meaning MCQ",
    context_cloze_mcq: "Context cloze MCQ",
    character_to_pinyin_typing: "Character → pinyin typing",
  }[value] ?? value;
}

export function StatusBadge({ status }: { status: string }) {
  const className = status.toLowerCase().replace(/ /g, "-");
  return <span className={`bkt-verification-status bkt-verification-status--${className}`}>{status}</span>;
}

function TraceTable({ trace, caption }: { trace: BktTraceStep[]; caption: string }) {
  if (trace.length === 0) return <p className="bkt-verification-empty-trace">No observations. Initial mastery is the configured cold-start prior.</p>;
  return (
    <div className="bkt-verification-table-wrap" tabIndex={0} role="region" aria-label={caption}>
      <table className="bkt-verification-table bkt-verification-trace-table">
        <caption>{caption}</caption>
        <thead><tr><th>Step</th><th>Prior</th><th>Observation</th><th>Guess</th><th>Slip</th><th>Posterior</th><th>+ learning</th><th>Resulting P(L)</th></tr></thead>
        <tbody>
          {trace.map((step) => (
            <tr key={step.step}>
              <td>{step.step}</td>
              <td>{formatProbability(step.prior)}</td>
              <td><span className={step.correct ? "bkt-verification-correct" : "bkt-verification-incorrect"}>{step.observation}</span><small>{formatQuestionType(step.questionType)}</small></td>
              <td>{step.guess.toFixed(2)}</td>
              <td>{step.slip.toFixed(2)}</td>
              <td>{formatProbability(step.posterior)}</td>
              <td>{step.learningTransition.toFixed(2)}</td>
              <td><strong>{formatProbability(step.resultingMastery)}</strong></td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function InputSummary({ input }: { input: GoldenCheck["input"] }) {
  if (input.length === 0) return <code>[]</code>;
  return <span className="bkt-verification-input-list">{input.map((item, index) => <span key={`${item.questionType}-${index}`} className={item.correct ? "is-correct" : "is-incorrect"}>{index + 1}. {item.correct ? "Correct" : "Incorrect"} · {formatQuestionType(item.questionType)}</span>)}</span>;
}

function Outcome({ result }: { result: VerificationResult }) {
  return <StatusBadge status={result} />;
}

export function GoldenSection({ checks, summary, contractStatus }: { checks: GoldenCheck[]; summary: { passed: number; total: number }; contractStatus: string }) {
  const [expanded, setExpanded] = useState(checks[0]?.id ?? "");
  const expandedCheck = checks.find((check) => check.id === expanded);
  return (
    <section className="bkt-verification-section" aria-labelledby="bkt-golden-title">
      <div className="bkt-verification-section-heading">
        <div><span className="admin-eyebrow">A · Canonical inputs</span><h2 id="bkt-golden-title">Golden BKT Checks</h2><p>Fixed, versioned vectors compare known outputs with the production replay. Expected values are not generated by the production updater.</p></div>
        <div className="bkt-verification-heading-meta"><Outcome result={contractStatus === "MATCH" && summary.passed === summary.total ? "PASS" : contractStatus !== "MATCH" ? "MODEL CONTRACT CHANGED" : "FAIL"} /><span>{summary.passed} / {summary.total} PASS</span></div>
      </div>
      <div className="bkt-verification-table-wrap" tabIndex={0} role="region" aria-label="Golden BKT checks">
        <table className="bkt-verification-table bkt-verification-golden-table">
          <caption>Versioned golden BKT scenarios</caption>
          <thead><tr><th>Scenario</th><th>Input</th><th>Expected</th><th>Actual</th><th>Result</th><th><span className="bkt-verification-visually-hidden">Trace</span></th></tr></thead>
          <tbody>
            {checks.map((check) => (
              <tr key={check.id}>
                <td><strong>{check.scenario}</strong></td>
                <td><InputSummary input={check.input} /></td>
                <td><span>{formatProbability(check.expected.pLearned)}</span><small>{check.expected.observationCount} observations · {check.expected.status}</small></td>
                <td><span>{formatProbability(check.actual.pLearned)}</span><small>{check.actual.observationCount} observations · {check.actual.status}</small></td>
                <td><Outcome result={check.result} /></td>
                <td><button type="button" className="bkt-verification-link-button" aria-expanded={expanded === check.id} onClick={() => setExpanded(expanded === check.id ? "" : check.id)}>{expanded === check.id ? "Hide trace" : "Show trace"}</button></td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      {expandedCheck && (
        <div className="bkt-verification-trace-detail">
          <div className="bkt-verification-detail-heading"><div><span className="admin-eyebrow">Step trace</span><h3>{expandedCheck.scenario}</h3></div><span>tolerance ± {expandedCheck.tolerance}</span></div>
          <div className="bkt-verification-trace-columns">
            <article><h4>Expected reference calculation</h4><TraceTable trace={expandedCheck.expected.trace} caption={`${expandedCheck.scenario} expected calculation`} /></article>
            <article><h4>Actual production replay</h4><TraceTable trace={expandedCheck.actual.trace} caption={`${expandedCheck.scenario} actual calculation`} /></article>
          </div>
        </div>
      )}
    </section>
  );
}

function EvidenceDetail({ item }: { item: EvidenceItem }) {
  return (
    <details className="bkt-verification-evidence-item">
      <summary><span><strong>#{item.order}</strong> {item.activityType} · {formatQuestionType(item.questionType)}</span><span className="bkt-verification-summary-meta"><span className={item.correct ? "bkt-verification-correct" : "bkt-verification-incorrect"}>{item.correct ? "Correct" : "Incorrect"}</span><span className={`bkt-verification-origin bkt-verification-origin--${item.evidenceOrigin.toLowerCase()}`}>{item.evidenceOrigin}</span></span></summary>
      <div className="bkt-verification-evidence-grid">
        <div><span>Timestamp</span><strong>{item.timestamp ? new Date(item.timestamp).toLocaleString() : "Not recorded"}</strong></div>
        <div><span>Quiz mode</span><strong>{item.quizMode ?? "—"}</strong></div>
        <div><span>Selected answer</span><strong>{item.selectedAnswer ?? "—"}</strong></div>
        <div><span>Expected answer</span><strong>{item.correctAnswer ?? "—"}</strong></div>
        <div><span>Resolver</span><strong>{item.resolver ?? "—"}</strong></div>
        <div><span>Item</span><strong>{item.itemId ?? "—"}</strong></div>
      </div>
      <details className="bkt-verification-technical"><summary>Technical details</summary><pre>{JSON.stringify(item.technical, null, 2)}</pre></details>
    </details>
  );
}

function ComparisonTable({ trace }: { trace: LiveTrace }) {
  return (
    <div className="bkt-verification-table-wrap" tabIndex={0} role="region" aria-label="Expected and actual BKT trace">
      <table className="bkt-verification-table bkt-verification-compare-table">
        <caption>Expected reference replay versus current production output</caption>
        <thead><tr><th>Step</th><th>Observation</th><th>Expected P(L)</th><th>Actual P(L)</th><th>Difference</th></tr></thead>
        <tbody>
          {trace.expectedTrace.map((expected, index) => {
            const actual = trace.actualTrace[index];
            const difference = actual ? actual.resultingMastery - expected.resultingMastery : Number.NaN;
            return <tr key={expected.step}><td>{expected.step}</td><td>{expected.observation}<small>{formatQuestionType(expected.questionType)}</small></td><td>{formatProbability(expected.resultingMastery)}</td><td>{actual ? formatProbability(actual.resultingMastery) : "—"}</td><td>{Number.isFinite(difference) ? difference.toFixed(9) : "—"}</td></tr>;
          })}
        </tbody>
      </table>
    </div>
  );
}

function SummaryMetric({ label, value, detail }: { label: string; value: string; detail?: string }) {
  return <div className="bkt-verification-live-metric"><span>{label}</span><strong>{value}</strong>{detail && <small>{detail}</small>}</div>;
}

export function LiveSection({
  students,
  selectedStudentId,
  selectedWordId,
  studentQuery,
  wordQuery,
  traceData,
  onStudentChange,
  onStudentQueryChange,
  onWordChange,
  onWordQueryChange,
  onPreset,
}: {
  students: VerificationStudent[];
  selectedStudentId: string;
  selectedWordId: string;
  studentQuery: string;
  wordQuery: string;
  traceData: { words: VerificationWord[]; presets: Array<{ id: string; label: string; wordId: string }>; trace: LiveTrace | null } | null;
  onStudentChange: (value: string) => void;
  onStudentQueryChange: (value: string) => void;
  onWordChange: (value: string) => void;
  onWordQueryChange: (value: string) => void;
  onPreset: (wordId: string) => void;
}) {
  const trace = traceData?.trace ?? null;
  const normalizedStudentQuery = studentQuery.trim().toLowerCase();
  const normalizedQuery = wordQuery.trim().toLowerCase();
  const visibleStudents = students.filter((row) => !normalizedStudentQuery || `${row.studentId} ${row.name}`.toLowerCase().includes(normalizedStudentQuery));
  const words = (traceData?.words ?? []).filter((word) => !normalizedQuery || `${word.word} ${word.wordId} ${word.meaning ?? ""}`.toLowerCase().includes(normalizedQuery));
  const student = students.find((row) => row.studentId === selectedStudentId);
  return (
    <section className="bkt-verification-section" aria-labelledby="bkt-live-title">
      <div className="bkt-verification-section-heading"><div><span className="admin-eyebrow">B · Persisted evidence</span><h2 id="bkt-live-title">Live Student Trace</h2><p>Select a student and known vocabulary word to inspect the evidence ledger and compare an independent replay with current mastery.</p></div>{trace && <Outcome result={trace.verification} />}</div>
      <div className="bkt-verification-selector-panel">
        <label>Student search<input value={studentQuery} onChange={(event) => onStudentQueryChange(event.target.value)} placeholder="SIM001 or name" /></label>
        <label>Student<select value={selectedStudentId} onChange={(event) => onStudentChange(event.target.value)}><option value="">Select a student</option>{visibleStudents.map((row) => <option key={row.studentId} value={row.studentId}>{row.studentId} · {row.name}</option>)}</select></label>
        <label>Word search<input value={wordQuery} onChange={(event) => onWordQueryChange(event.target.value)} placeholder="Search word or word ID" /></label>
        <label>Word<select value={selectedWordId} onChange={(event) => onWordChange(event.target.value)} disabled={!selectedStudentId || words.length === 0}><option value="">Select a word</option>{words.map((word) => <option key={word.wordId} value={word.wordId}>{word.word} · {word.wordId} · {word.observationCount} obs</option>)}</select></label>
      </div>
      {traceData && traceData.presets.length > 0 && <div className="bkt-verification-presets"><span>Quick verification presets</span>{traceData.presets.map((preset) => <button type="button" key={preset.id} className="bkt-verification-link-button" onClick={() => onPreset(preset.wordId)}>{preset.label}</button>)}</div>}
      {!selectedStudentId && <p className="bkt-verification-empty-state">Choose a student to load their known vocabulary.</p>}
      {selectedStudentId && traceData && !trace && <p className="bkt-verification-empty-state">No published vocabulary is available for this student.</p>}
      {trace && (
        <div className="bkt-verification-live-body">
          {(student?.isTestAccount || trace.syntheticTestData) && <div className="bkt-verification-synthetic-note"><strong>Synthetic test data</strong><span>Not valid research evidence. Evidence origin is shown on every observation.</span></div>}
          {trace.provenance === "MIXED" && <div className="bkt-verification-warning"><strong>Mixed provenance</strong><span>This trace contains both REAL and SYNTHETIC evidence. They are not hidden or relabeled.</span></div>}
          <div className="bkt-verification-word-heading"><div><span className="admin-eyebrow">Selected word</span><h3 lang="zh-Hant">{trace.word.word}</h3><p>{trace.word.meaning ?? trace.word.wordId} · <code>{trace.word.wordId}</code></p></div><span className={`bkt-verification-origin bkt-verification-origin--${trace.provenance.toLowerCase()}`}>{trace.provenance}</span></div>
          <div className="bkt-verification-live-metrics"><SummaryMetric label="Evidence" value={String(trace.evidenceCount)} /><SummaryMetric label="Current P(L)" value={formatProbability(trace.comparison.pLearned.actual)} /><SummaryMetric label="BKT status" value={trace.comparison.status.actual} /><SummaryMetric label="Review status" value={trace.reviewStatus} /></div>
          <div className="bkt-verification-cold-start"><div><span>Cold-start source</span><strong>{trace.coldStart.source}</strong></div>{trace.coldStart.source === "Placement Chapter Prior" ? <div className="bkt-verification-cold-start-details"><span>Chapter <strong>{trace.coldStart.chapter}</strong></span><span>Placement <strong>{trace.coldStart.placementResult}</strong></span><span>Raw score <strong>{trace.coldStart.rawScore?.toFixed(3)}</strong></span><span>Shrinkage <strong>{trace.coldStart.shrinkageWeight?.toFixed(3)}</strong></span><span>Applied P(L0) <strong>{formatProbability(trace.coldStart.pL0)}</strong></span></div> : <div><span>P(L0)</span><strong>{formatProbability(trace.coldStart.pL0)}</strong></div>}</div>
          <section className="bkt-verification-evidence"><div className="bkt-verification-subheading"><h4>Evidence history</h4><span>{trace.evidenceCount} observation{trace.evidenceCount === 1 ? "" : "s"}</span></div>{trace.evidence.length === 0 ? <p className="bkt-verification-empty-trace">No BKT observations. The word is known vocabulary but remains unassessed.</p> : <div className="bkt-verification-evidence-list">{trace.evidence.map((item) => <EvidenceDetail item={item} key={`${item.order}-${item.itemId}`} />)}</div>}</section>
          <section className="bkt-verification-bkt-trace"><div className="bkt-verification-subheading"><div><h4>BKT trace</h4><span>Expected reference calculation versus actual production replay</span></div><Outcome result={trace.verification} /></div><div className="bkt-verification-live-comparison"><SummaryMetric label="Observations" value={`${trace.comparison.observationCount.expected} / ${trace.comparison.observationCount.actual}`} detail="expected / actual" /><SummaryMetric label="P(L)" value={`${formatProbability(trace.comparison.pLearned.expected)} / ${formatProbability(trace.comparison.pLearned.actual)}`} detail="expected / actual" /><SummaryMetric label="Status" value={`${trace.comparison.status.expected} / ${trace.comparison.status.actual}`} detail="expected / actual" /></div>{trace.expectedTrace.length > 0 && <ComparisonTable trace={trace} />}<details className="bkt-verification-technical"><summary>Show calculation fields</summary><div className="bkt-verification-trace-columns"><article><h5>Expected</h5><TraceTable trace={trace.expectedTrace} caption="Expected live BKT calculation" /></article><article><h5>Actual</h5><TraceTable trace={trace.actualTrace} caption="Actual live BKT calculation" /></article></div></details></section>
        </div>
      )}
    </section>
  );
}
