import { useMemo, useState } from "react";
import { canUseDatabase, createCustomStory } from "../services/database";
import "./TeacherImageBuilderPage.css";

const BACKEND_URL =
  import.meta.env.VITE_BACKEND_URL ||
  (import.meta.env.DEV ? "http://127.0.0.1:8000" : "");
const CUSTOM_STORY_STORAGE_KEY = "teacherCustomStories";

interface GeneratedFrame {
  index: number;
  title: string;
  student_prompt: string;
  vocabulary: string[];
  image_prompt: string;
  image_url: string;
}

interface GeneratedStory {
  provider: string;
  title: string;
  learning_goal: string;
  frames: GeneratedFrame[];
}

export default function TeacherImageBuilderPage() {
  const [situation, setSituation] = useState(
    "A student forgets an EasyCard at Taipei MRT and asks classmates and station staff for help.",
  );
  const [level, setLevel] = useState("Beginner speaking");
  const [style, setStyle] = useState("warm watercolor comic for students");
  const [languageFocus, setLanguageFocus] = useState(
    "who, where, first event, problem, help, solution, feeling",
  );
  const [story, setStory] = useState<GeneratedStory | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");

  const preparedFrames = useMemo(() => story?.frames.length ?? 0, [story]);

  const generateStory = async () => {
    setError("");
    setNotice("");

    if (situation.trim().length < 8) {
      setError("Describe a real-life situation with enough detail for six scenes.");
      return;
    }

    setIsGenerating(true);
    try {
      const response = await fetch(`${getBackendUrl()}/api/generate-story-images`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          situation,
          level,
          style,
          language_focus: languageFocus,
        }),
      });

      if (!response.ok) {
        const data = await readErrorResponse(response);
        throw new Error(data.detail || "Could not generate the story images.");
      }

      setStory(await response.json());
    } catch (err) {
      setError(formatBackendError(err, BACKEND_URL || "the configured backend"));
    } finally {
      setIsGenerating(false);
    }
  };

  const updateFrame = (
    index: number,
    field: "title" | "student_prompt" | "image_prompt",
    value: string,
  ) => {
    setStory((current) => {
      if (!current) {
        return current;
      }

      return {
        ...current,
        frames: current.frames.map((frame, frameIndex) =>
          frameIndex === index ? { ...frame, [field]: value } : frame,
        ),
      };
    });
    setNotice("");
  };

  const updateVocabulary = (index: number, value: string) => {
    setStory((current) => {
      if (!current) {
        return current;
      }

      return {
        ...current,
        frames: current.frames.map((frame, frameIndex) =>
          frameIndex === index
            ? {
                ...frame,
                vocabulary: value
                  .split(",")
                  .map((word) => word.trim())
                  .filter(Boolean),
              }
            : frame,
        ),
      };
    });
    setNotice("");
  };

  const saveGeneratedStory = async () => {
    if (!story || story.frames.length !== 6) {
      setError("Generate six story frames before saving.");
      return;
    }

    const savedStory = {
      id: `ai-story-${Date.now()}`,
      title: story.title,
      learningGoal: story.learning_goal,
      level,
      frames: story.frames.map((frame) => ({
        imageUrl: frame.image_url,
        prompt: frame.student_prompt,
        vocabulary: frame.vocabulary.join(", "),
      })),
    };
    const stored = loadCustomStories();

    try {
      window.localStorage.setItem(
        CUSTOM_STORY_STORAGE_KEY,
        JSON.stringify([savedStory, ...stored]),
      );
      if (canUseDatabase()) {
        await createCustomStory(savedStory);
      }
      setNotice("Generated story saved to the teacher story library.");
      setError("");
    } catch {
      setError("Could not save this story.");
    }
  };

  return (
    <main className="teacher-image-page">
      <section className="teacher-image-hero">
        <div>
          <p className="stories-kicker">AI materials</p>
          <h1>Generate Six Picture Cues</h1>
          <p>
            Turn one classroom situation into a connected six-frame speaking
            story with prompts, vocabulary, and image previews for students.
          </p>
        </div>
        <div className="teacher-image-status">
          <span>Frames</span>
          <strong>{preparedFrames}/6</strong>
          <p>{story ? `Generated by ${story.provider}` : "Ready to build"}</p>
        </div>
      </section>

      <section className="teacher-image-builder">
        <form
          className="teacher-image-form"
          onSubmit={(event) => {
            event.preventDefault();
            generateStory();
          }}
        >
          <label>
            Situation context
            <textarea
              value={situation}
              onChange={(event) => setSituation(event.target.value)}
              rows={4}
              placeholder="Example: Students visit a night market, lose a wallet, ask for help, and find it."
            />
          </label>

          <div className="teacher-image-form-grid">
            <label>
              Student level
              <select value={level} onChange={(event) => setLevel(event.target.value)}>
                <option>Beginner speaking</option>
                <option>Intermediate speaking</option>
                <option>Advanced storytelling</option>
              </select>
            </label>
            <label>
              Visual style
              <input
                value={style}
                onChange={(event) => setStyle(event.target.value)}
                placeholder="comic, watercolor, friendly classroom style"
              />
            </label>
          </div>

          <label>
            Language focus
            <input
              value={languageFocus}
              onChange={(event) => setLanguageFocus(event.target.value)}
              placeholder="story sequence, asking for help, feeling words"
            />
          </label>

          {error && <div className="teacher-image-error" role="alert">{error}</div>}
          {notice && <div className="teacher-image-success" role="status">{notice}</div>}

          <div className="teacher-image-actions">
            <button type="submit" className="btn-generate-images" disabled={isGenerating}>
              {isGenerating ? "Generating..." : "Generate 6 images"}
            </button>
            <button
              type="button"
              className="btn-save-generated"
              onClick={saveGeneratedStory}
              disabled={!story || isGenerating}
            >
              Save to story library
            </button>
          </div>
        </form>

        <aside className="teacher-image-guide">
          <h2>Good situation contexts</h2>
          <ul>
            <li>Use one real-life place students recognize.</li>
            <li>Include one problem students can solve through speaking.</li>
            <li>Ask for a clear ending feeling or lesson.</li>
          </ul>
        </aside>
      </section>

      {story && (
        <section className="generated-story-panel" aria-label="Generated six image story">
          <div className="generated-story-header">
            <div>
              <p className="stories-kicker">{story.provider}</p>
              <h2>{story.title}</h2>
              <p>{story.learning_goal}</p>
            </div>
          </div>

          <div className="generated-frame-grid">
            {story.frames.map((frame, index) => (
              <article className="generated-frame-card" key={frame.index}>
                <div className="generated-frame-image">
                  <img src={frame.image_url} alt={`Generated story frame ${frame.index}`} />
                </div>
                <div className="generated-frame-body">
                  <label>
                    Scene title
                    <input
                      value={frame.title}
                      onChange={(event) =>
                        updateFrame(index, "title", event.target.value)
                      }
                    />
                  </label>
                  <label>
                    Student speaking prompt
                    <textarea
                      value={frame.student_prompt}
                      onChange={(event) =>
                        updateFrame(index, "student_prompt", event.target.value)
                      }
                      rows={2}
                    />
                  </label>
                  <label>
                    Vocabulary
                    <input
                      value={frame.vocabulary.join(", ")}
                      onChange={(event) => updateVocabulary(index, event.target.value)}
                    />
                  </label>
                  <details className="image-prompt-details">
                    <summary>Image prompt</summary>
                    <textarea
                      value={frame.image_prompt}
                      onChange={(event) =>
                        updateFrame(index, "image_prompt", event.target.value)
                      }
                      rows={3}
                    />
                  </details>
                </div>
              </article>
            ))}
          </div>
        </section>
      )}
    </main>
  );
}

function loadCustomStories() {
  try {
    const stored = window.localStorage.getItem(CUSTOM_STORY_STORAGE_KEY);
    return stored ? JSON.parse(stored) : [];
  } catch {
    return [];
  }
}

async function readErrorResponse(response: Response): Promise<{ detail?: string }> {
  try {
    return await response.json();
  } catch {
    return { detail: `${response.status} ${response.statusText}` };
  }
}

function getBackendUrl(): string {
  if (BACKEND_URL) {
    return BACKEND_URL;
  }

  throw new Error("Set VITE_BACKEND_URL to use AI story image generation.");
}

function formatBackendError(error: unknown, backendUrl: string): string {
  const message = error instanceof Error ? error.message : String(error);
  if (message.includes("Failed to fetch") || message.includes("NetworkError")) {
    return `Cannot reach the AI generation backend at ${backendUrl}. Start the FastAPI backend, then try again.`;
  }

  return message || "Generation failed.";
}
