"""One command to reproduce the OMPAL validation.

    python -m benchmarking.validation_cli
    python -m benchmarking.validation_cli --limit 50

Reads the corpus and the cached scoring, recomputes every metric, exports the
error tables and writes the research summary. Scoring is *not* re-run when a
cached result file exists — 1,850 files through Praat takes minutes and the
audio has not changed.

Nothing here modifies the analyzer, the pass threshold, or the corpus. It
reports; it does not tune.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Sequence

from benchmarking.error_analysis import build_rows, export, summarize
from benchmarking.ompal_corpus import (
    JOIN_EXACT,
    OmpalUtterance,
    join_summary,
    load_utterances,
)
from benchmarking.ompal_report import PRODUCTION_THRESHOLD, build_report
from benchmarking.ompal_runner import load_scored

DEFAULT_CORPUS = Path("private-data/ompal")
DEFAULT_SCORED = Path("private-data/ompal-scored.jsonl")
DEFAULT_RESULTS = Path("benchmarking/results")


def _percent(value: Any) -> str:
    return f"{value * 100:.1f} %" if isinstance(value, (int, float)) else "NA"


def _number(value: Any, digits: int = 3) -> str:
    return f"{value:.{digits}f}" if isinstance(value, (int, float)) else "NA"


def _agreement_table(metrics: dict[str, Any]) -> str:
    if not metrics.get("n"):
        return "_No comparable items._\n"
    rows = [
        ("N", str(metrics["n"])),
        ("Accuracy", _number(metrics.get("accuracy"))),
        ("Precision", _number(metrics.get("precision"))),
        ("Recall (sensitivity)", _number(metrics.get("recall"))),
        ("Specificity", _number(metrics.get("specificity"))),
        ("Balanced accuracy", _number(metrics.get("balanced_accuracy"))),
        ("F1", _number(metrics.get("f1"))),
        ("Cohen's kappa", _number(metrics.get("cohen_kappa"), 4)),
        ("Matthews correlation (MCC)", _number(metrics.get("matthews_correlation"), 4)),
        ("True positive", str(metrics.get("true_positive"))),
        ("True negative", str(metrics.get("true_negative"))),
        ("False positive", str(metrics.get("false_positive"))),
        ("False negative", str(metrics.get("false_negative"))),
    ]
    body = "\n".join(f"| {name} | {value} |" for name, value in rows)
    return f"| Metric | Value |\n|---|---|\n{body}\n"


def render_summary(
    *,
    report_a: dict[str, Any],
    report_b: dict[str, Any],
    provenance: dict[str, Any],
    error_summary: dict[str, Any],
    exports: dict[str, int],
    threshold: float,
) -> str:
    """The research report. Cautious by construction: it states agreement
    levels and never asserts that the system is validated."""
    pf_a = report_a["pass_fail_agreement"]
    pf_b = report_b["pass_fail_agreement"]
    protocol = report_b["benchmark_protocol"]
    ceiling = report_b["human_ceiling"]
    sentence = report_b["score_agreement"]
    segmental = report_b["segmental_support"]

    def tone_rows() -> str:
        lines = []
        for tone, metrics in sorted(error_summary["by_expected_tone"].items()):
            if tone == "NA" or not metrics.get("n"):
                continue
            lines.append(
                f"| T{tone} | {metrics['n']} | {_number(metrics.get('accuracy'))} | "
                f"{_number(metrics.get('recall'))} | {_number(metrics.get('specificity'))} | "
                f"{_number(metrics.get('cohen_kappa'), 4)} | "
                f"{_percent(metrics.get('false_rejection_rate'))} | "
                f"{_percent(metrics.get('false_acceptance_rate'))} |"
            )
        return "\n".join(lines)

    kappa_a = pf_a.get("cohen_kappa")
    kappa_b = pf_b.get("cohen_kappa")
    drift = (
        abs(kappa_a - kappa_b)
        if isinstance(kappa_a, (int, float)) and isinstance(kappa_b, (int, float))
        else None
    )

    return f"""# OMPAL validation summary

Generated by `python -m benchmarking.validation_cli`. Read-only: no model,
threshold, or corpus file was modified to produce it.

## 1. Dataset

| | |
|---|---|
| Corpus | {protocol['citation']} |
| Utterances with audio | {provenance['total']} |
| Speakers scored | {protocol['speaker_count']} |
| Recordings scored | {protocol['recording_count']} |
| Rated word items compared | {protocol['rated_word_count']} |

{protocol['population_caveat']}

## 2. OMPAL human reference

Word level, per rater: consonant 0/1, vowel 0/1, tone 0/1.
Sentence level, per rater: accuracy, fluency, prosody on a 1–5 rubric.
The rubric is used as published; no label was altered or inferred.

| Rater panel | Value |
|---|---|
| Raters per item | {ceiling.get('rater_count')} |
| Items with a full panel | {ceiling.get('item_count')} |
| Mean pairwise Cohen's kappa between raters | {_number(ceiling.get('mean_pairwise_cohen_kappa'))} |
| Fleiss' kappa (human ceiling) | {_number(ceiling.get('fleiss_kappa'))} |
| Unanimous items | {_percent(ceiling.get('unanimous_rate'))} |

The human ceiling matters for reading every number below: experts agree with
each other at kappa {_number(ceiling.get('fleiss_kappa'))}, so that is the
practical maximum any system can be asked to reach against this panel.

## 3. ID matching and exclusions

| Join source | Utterances |
|---|---|
| Exact ID match | {provenance['by_join_source'].get(JOIN_EXACT, 0)} |
| Deterministic remap | {provenance['by_join_source'].get('deterministic_remap', 0)} |
| Native, scalar ratings only (no per-rater labels) | {provenance['by_join_source'].get('native_scalar_only', 0)} |

The remap is documented and verified in `ompal_id_join_audit.md`; it is applied
in the loader only and the corpus files are untouched. Native utterances are
excluded from every inter-rater statistic because OMPAL publishes no per-rater
breakdown for them.

Word items excluded from the comparison:

| Reason | Count |
|---|---|
{chr(10).join(f"| {name} | {count} |" for name, count in sorted(report_b['exclusions'].items()))}

## 4. Current automated system

Pitch is extracted with Praat (Parselmouth), syllable boundaries come from an
energy aligner, and each syllable is scored by a rule-based contour-direction
heuristic. A word passes when every character scores at or above
{threshold:g}. {protocol['threshold_warning']}

## 5. Supported criteria

Word-level tone, sentence accuracy (as a 0–100 tone-accuracy score), sentence
fluency (as a 0–100 fluency score).

## 6. Unsupported criteria

| Criterion | Human labels available | Machine output | Why unsupported |
|---|---|---|---|
| Consonant | {segmental['consonant']['human_label_count']} | none | {segmental['consonant']['reason']} |
| Vowel | {segmental['vowel']['human_label_count']} | {segmental['vowel']['system_output']} | {segmental['vowel']['reason']} |
| Sentence prosody | {sentence['prosody']['human_label_count']} | none | {sentence['prosody']['reason']} |

No prediction was fabricated for any of these.

## 7. Word-level tone validation

### Cohort A — exact-ID utterances only

{_agreement_table(pf_a)}

### Cohort B — expanded set, including the deterministic remap

{_agreement_table(pf_b)}

**Does the expansion change the conclusion?** Cohen's kappa moves from
{_number(kappa_a, 4)} (A) to {_number(kappa_b, 4)} (B), a difference of
{_number(drift, 4)} on {pf_b.get('n', 0) - pf_a.get('n', 0)} additional word items
(+{_percent((pf_b.get('n', 0) - pf_a.get('n', 0)) / pf_a['n']) if pf_a.get('n') else 'NA'}). The
larger sample does not alter the picture; it narrows the uncertainty around the
same result. All figures below use cohort B.

### Confusion matrix (cohort B)

Positive class = "pronounced correctly".

| | Human: correct | Human: incorrect |
|---|---|---|
| **System: correct** | {pf_b.get('true_positive', 'NA')} | {pf_b.get('false_positive', 'NA')} |
| **System: incorrect** | {pf_b.get('false_negative', 'NA')} | {pf_b.get('true_negative', 'NA')} |

### Per expected tone

| Tone | N | Accuracy | Recall | Specificity | Kappa | False rejection | False acceptance |
|---|---|---|---|---|---|---|---|
{tone_rows()}

## 8. False acceptance

Human marked the item incorrect, the system passed it.

| | Value |
|---|---|
| Count | {pf_b.get('false_acceptance_count', 'NA')} |
| Denominator (items humans marked incorrect) | {pf_b.get('false_acceptance_denominator', 'NA')} |
| Rate | {_percent(pf_b.get('false_acceptance_rate'))} |

## 9. False rejection

Human marked the item correct, the system failed it.

| | Value |
|---|---|
| Count | {pf_b.get('false_rejection_count', 'NA')} |
| Denominator (items humans marked correct) | {pf_b.get('false_rejection_denominator', 'NA')} |
| Rate | {_percent(pf_b.get('false_rejection_rate'))} |

How far below the pass bar the false rejections sat:

| Distance below threshold | Count |
|---|---|
{chr(10).join(f"| {name} | {count} |" for name, count in error_summary['false_rejection_by_score_distance'].items())}

## 10. Error analysis

Exported tables:

{chr(10).join(f"- `{name}` — {count} rows" for name, count in exports.items())}

Most frequently false-rejected words:

{', '.join(f"{word} ({count})" for word, count in error_summary['most_false_rejected_words'][:10])}

Dimensions requested but not available from the cached scoring:

{chr(10).join(f"- {name}: {reason}" for name, reason in error_summary['unavailable_dimensions'].items())}

## 11. Sentence accuracy

| | Value |
|---|---|
| N | {sentence['accuracy']['n']} |
| Spearman rho | {_number(sentence['accuracy'].get('spearman_correlation'))} |
| Pearson r (secondary) | {_number(sentence['accuracy'].get('pearson_correlation'))} |
| Mean human rating (1–5) | {_number(sentence['accuracy'].get('mean_human_rating'), 2)} |
| Mean system score (0–100) | {_number(sentence['accuracy'].get('mean_system_score'), 1)} |

{report_b['score_agreement']['note']}

## 12. Sentence fluency

| | Value |
|---|---|
| N | {sentence['fluency']['n']} |
| Spearman rho | {_number(sentence['fluency'].get('spearman_correlation'))} |
| Pearson r (secondary) | {_number(sentence['fluency'].get('pearson_correlation'))} |
| Mean human rating (1–5) | {_number(sentence['fluency'].get('mean_human_rating'), 2)} |
| Mean system score (0–100) | {_number(sentence['fluency'].get('mean_system_score'), 1)} |

Reported without a verdict: no pass criterion for this correlation was defined
in advance, so calling it adequate or inadequate here would be a judgement made
after seeing the number.

## 13. Prosody

Unsupported. {sentence['prosody']['reason']}

## 14. Limitations

- The learners are French-L1 reading prompted sentences. Results do not
  transfer automatically to other first languages or to spontaneous speech.
- Native utterances carry no per-rater labels and sit outside every agreement
  statistic.
- Neutral-tone words are excluded: the scorer returns a constant for them, so
  they measure nothing.
- Words the analyzer declined to judge are excluded rather than counted as
  failures; that choice favours the system.
- Per-syllable duration, F0 summaries and alignment quality are not stored by
  the cached scoring, so the error tables cannot yet attribute failures to
  those factors.
- The pass threshold was not chosen using this corpus, and was not changed for
  this analysis. Tuning it against these results would be test-set leakage.

## 15. Interpretation

The current tone assessment showed low agreement with OMPAL expert
annotations: Cohen's kappa {_number(kappa_b, 4)} against the rater majority,
where the experts agree with each other at {_number(ceiling.get('fleiss_kappa'))}.
An accuracy of {_number(pf_b.get('accuracy'))} on a corpus where
{_percent(pf_b['false_rejection_denominator'] / pf_b['n']) if pf_b.get('n') else 'NA'} of items are rated
correct is close to what a system that mostly guessed the majority class would
obtain, which is why kappa rather than accuracy is the figure to read.

The errors are heavily asymmetric. The system rejected
{_percent(pf_b.get('false_rejection_rate'))} of the items experts judged correct,
against {_percent(pf_b.get('false_acceptance_rate'))} false acceptance. Per tone,
the pattern is consistent: level tone is passed almost indiscriminately (high
recall, very low specificity) while rising and falling tones are rejected at
high rates. Most false rejections were not marginal — the majority sat well
below the pass bar rather than just under it — so this does not look like a
threshold that is merely set a little high.

These results describe agreement with one expert-annotated corpus. They are not
a statement that the system is validated, and they are not evidence about
learners of a different first language.

## 16. Recommended next step

The evidence points at the tone scorer's contour model rather than at the
threshold or at missing segmental assessment. Before considering any new model,
the following should be established, in order:

1. Extend the scoring records to carry per-syllable duration, F0 summary
   features and alignment quality, then re-run. Without them the error tables
   cannot separate "the aligner cut the syllable in the wrong place" from "the
   contour heuristic misreads normal declination".
2. Check whether the rising/falling rejection rates concentrate in short
   syllables or in specific positions in the utterance, which would implicate
   alignment rather than the tone rule.
3. Only if the failure survives that analysis does a different acoustic model
   become the indicated remedy — and consonant/vowel assessment remains
   unsupported regardless, because no phoneme-level alignment exists.

No model change is proposed by this report.
"""


def run(
    *,
    corpus_root: Path,
    scored_path: Path,
    results_dir: Path,
    limit: int | None = None,
    threshold: float = PRODUCTION_THRESHOLD,
) -> dict[str, Any]:
    if not corpus_root.is_dir():
        raise SystemExit(f"OMPAL corpus not found at {corpus_root}")
    if not scored_path.is_file():
        raise SystemExit(
            f"No cached scoring at {scored_path}. Run the OMPAL benchmark first; "
            "this command deliberately does not score 1,850 files implicitly."
        )

    utterances: Sequence[OmpalUtterance] = load_utterances(corpus_root)
    scored_rows = load_scored(scored_path)
    if limit is not None:
        # Deterministic subset, and a useful one: utterances are already sorted
        # by ID, but the first of them are native recordings that carry no
        # per-rater labels and so produce no comparable rows. Sampling from the
        # utterances that can actually be validated makes --limit a pilot of
        # the pipeline rather than a pilot of the exclusion logic.
        comparable = [u for u in utterances if u.has_per_rater_labels]
        keep = {utterance.utterance_id for utterance in comparable[:limit]}
        utterances = [u for u in utterances if u.utterance_id in keep]
        scored_rows = [r for r in scored_rows if r.get("utterance_id") in keep]

    failures = [row for row in scored_rows if row.get("error")]
    for row in failures:
        print(
            f"  scoring failure: {row.get('utterance_id')} -> {row.get('error')}",
            file=sys.stderr,
        )

    exact_only = [u for u in utterances if u.join_source == JOIN_EXACT]
    report_a = build_report(exact_only, scored_rows, threshold=threshold)
    report_b = build_report(utterances, scored_rows, threshold=threshold)

    rows = build_rows(utterances, scored_rows, threshold=threshold)
    error_summary = summarize(rows, threshold)
    exports = export(rows, results_dir)

    summary = render_summary(
        report_a=report_a,
        report_b=report_b,
        provenance=join_summary(utterances),
        error_summary=error_summary,
        exports=exports,
        threshold=threshold,
    )
    results_dir.mkdir(parents=True, exist_ok=True)
    (results_dir / "validation_summary.md").write_text(summary, encoding="utf-8")
    (results_dir / "validation_report.json").write_text(
        json.dumps(
            {
                "cohort_a_exact_id": report_a,
                "cohort_b_expanded": report_b,
                "error_summary": {
                    key: value
                    for key, value in error_summary.items()
                    if key != "error_counts"
                },
                "error_counts": dict(error_summary["error_counts"]),
            },
            ensure_ascii=False,
            indent=2,
            default=str,
        ),
        encoding="utf-8",
    )
    return {
        "utterances": len(utterances),
        "scoring_failures": len(failures),
        "rows": len(rows),
        "exports": exports,
    }


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--corpus", type=Path, default=DEFAULT_CORPUS)
    parser.add_argument("--scored", type=Path, default=DEFAULT_SCORED)
    parser.add_argument("--results", type=Path, default=DEFAULT_RESULTS)
    parser.add_argument(
        "--limit", type=int, default=None, help="pilot run over the first N utterances"
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=PRODUCTION_THRESHOLD,
        help="diagnosis only; the shipped threshold is not changed by this tool",
    )
    args = parser.parse_args(argv)

    outcome = run(
        corpus_root=args.corpus,
        scored_path=args.scored,
        results_dir=args.results,
        limit=args.limit,
        threshold=args.threshold,
    )
    print(json.dumps(outcome, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
